apiVersion: v1
kind: Service
metadata:
  name: amp-sql-svc
  labels:
    app: mysql-asset
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql-asset
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: amp-sql-deploy
spec:
  selector:
    matchLabels:
      app: mysql-asset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-asset
    spec:
      containers:
      - image: deepakkumarc/amp-sql:1.0
        name: amp-sql
        ports:
        - containerPort: 3306
          name: amp-sql

